Repository: plone.restapi


Branch: refs/heads/master
Date: 2020-03-10T16:02:28+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.restapi/commit/344c4f8c3dfd381710c7bf6e0a370310a068b68d

Fixed package install error with Python 3.6 without locale.

See https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272

Files changed:
A news/642.bugfix
M setup.py

b'diff --git a/news/642.bugfix b/news/642.bugfix\nnew file mode 100644\nindex 00000000..0473e7df\n--- /dev/null\n+++ b/news/642.bugfix\n@@ -0,0 +1,3 @@\n+Fixed package install error with Python 3.6 without locale.\n+See `coredev issue 642 <https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272>`_.\n+[maurits]\ndiff --git a/setup.py b/setup.py\nindex 4fdeda1f..ed0cf215 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -4,13 +4,29 @@\n \n version = \'6.3.1.dev0\'\n \n+\n+def read(filename):\n+    with open(filename) as myfile:\n+        try:\n+            return myfile.read()\n+        except UnicodeDecodeError:\n+            # Happens on one Jenkins node on Python 3.6,\n+            # so maybe it happens for users too.\n+            pass\n+    # Opening and reading as text failed, so retry opening as bytes.\n+    with open(filename, "rb") as myfile:\n+        contents = myfile.read()\n+        return contents.decode("utf-8")\n+\n long_description = (\n-    open("README.rst").read() + "\\n" + "Contributors\\n"\n-    "============\\n"\n+    read("README.rst")\n+    + "\\n"\n+    + "Contributors\\n"\n+    + "============\\n"\n     + "\\n"\n-    + open("CONTRIBUTORS.rst").read()\n+    + read("CONTRIBUTORS.rst")\n     + "\\n"\n-    + open("CHANGES.rst").read()\n+    + read("CHANGES.rst")\n     + "\\n"\n )\n \n'

Repository: plone.restapi


Branch: refs/heads/master
Date: 2020-03-10T18:14:46+01:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.restapi/commit/5e50f5bb5f46e8201ed604b33c07298c68450ee6

Merge pull request #879 from plone/maurits/fix-long-description-on-py36

Fixed package install error with Python 3.6 without locale.

Files changed:
A news/642.bugfix
M setup.py

b'diff --git a/news/642.bugfix b/news/642.bugfix\nnew file mode 100644\nindex 00000000..0473e7df\n--- /dev/null\n+++ b/news/642.bugfix\n@@ -0,0 +1,3 @@\n+Fixed package install error with Python 3.6 without locale.\n+See `coredev issue 642 <https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272>`_.\n+[maurits]\ndiff --git a/setup.py b/setup.py\nindex 4fdeda1f..ed0cf215 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -4,13 +4,29 @@\n \n version = \'6.3.1.dev0\'\n \n+\n+def read(filename):\n+    with open(filename) as myfile:\n+        try:\n+            return myfile.read()\n+        except UnicodeDecodeError:\n+            # Happens on one Jenkins node on Python 3.6,\n+            # so maybe it happens for users too.\n+            pass\n+    # Opening and reading as text failed, so retry opening as bytes.\n+    with open(filename, "rb") as myfile:\n+        contents = myfile.read()\n+        return contents.decode("utf-8")\n+\n long_description = (\n-    open("README.rst").read() + "\\n" + "Contributors\\n"\n-    "============\\n"\n+    read("README.rst")\n+    + "\\n"\n+    + "Contributors\\n"\n+    + "============\\n"\n     + "\\n"\n-    + open("CONTRIBUTORS.rst").read()\n+    + read("CONTRIBUTORS.rst")\n     + "\\n"\n-    + open("CHANGES.rst").read()\n+    + read("CHANGES.rst")\n     + "\\n"\n )\n \n'

