Repository: plone.dexterity


Branch: refs/heads/master
Date: 2020-03-10T11:37:59+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.dexterity/commit/7ccb5a0f45451ff1871825e78f812dfe4b9e8e95

Fixed package install error with Python 3.6 without system locale.

See https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272

Files changed:
A news/642.bugfix
M setup.py

b'diff --git a/news/642.bugfix b/news/642.bugfix\nnew file mode 100644\nindex 0000000..5e24633\n--- /dev/null\n+++ b/news/642.bugfix\n@@ -0,0 +1,3 @@\n+Fixed package install error with Python 3.6 without system locale.\n+See `coredev issue 642 <https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272>`_.\n+[maurits]\ndiff --git a/setup.py b/setup.py\nindex 34a251b..0b0fe7e 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -5,11 +5,26 @@\n \n version = \'2.9.6.dev0\'\n \n+\n+def read(filename):\n+    with open(filename) as myfile:\n+        try:\n+            return myfile.read()\n+        except UnicodeDecodeError:\n+            # Happens on one Jenkins node on Python 3.6,\n+            # so maybe it happens for users too.\n+            pass\n+    # Opening and reading as text failed, so retry opening as bytes.\n+    with open(filename, "rb") as myfile:\n+        contents = myfile.read()\n+        return contents.decode("utf-8")\n+\n short_description = """\\\n Framework for content types as filesystem code and TTW (Zope/CMF/Plone)\\\n """\n-long_description = open("README.rst").read() + "\\n"\n-long_description += open("CHANGES.rst").read()\n+long_description = read("README.rst")\n+long_description += "\\n"\n+long_description += read("CHANGES.rst")\n \n setup(\n     name=\'plone.dexterity\',\n'

Repository: plone.dexterity


Branch: refs/heads/master
Date: 2020-03-10T15:12:23+01:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.dexterity/commit/b61d09f80036e50952905d19ca7a43a09ab97612

Merge pull request #128 from plone/maurits/fix-long-description-on-py36

Fixed package install error with Python 3.6 without system locale.

Files changed:
A news/642.bugfix
M setup.py

b'diff --git a/news/642.bugfix b/news/642.bugfix\nnew file mode 100644\nindex 0000000..5e24633\n--- /dev/null\n+++ b/news/642.bugfix\n@@ -0,0 +1,3 @@\n+Fixed package install error with Python 3.6 without system locale.\n+See `coredev issue 642 <https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272>`_.\n+[maurits]\ndiff --git a/setup.py b/setup.py\nindex 34a251b..0b0fe7e 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -5,11 +5,26 @@\n \n version = \'2.9.6.dev0\'\n \n+\n+def read(filename):\n+    with open(filename) as myfile:\n+        try:\n+            return myfile.read()\n+        except UnicodeDecodeError:\n+            # Happens on one Jenkins node on Python 3.6,\n+            # so maybe it happens for users too.\n+            pass\n+    # Opening and reading as text failed, so retry opening as bytes.\n+    with open(filename, "rb") as myfile:\n+        contents = myfile.read()\n+        return contents.decode("utf-8")\n+\n short_description = """\\\n Framework for content types as filesystem code and TTW (Zope/CMF/Plone)\\\n """\n-long_description = open("README.rst").read() + "\\n"\n-long_description += open("CHANGES.rst").read()\n+long_description = read("README.rst")\n+long_description += "\\n"\n+long_description += read("CHANGES.rst")\n \n setup(\n     name=\'plone.dexterity\',\n'

