Repository: plone.app.robotframework


Branch: refs/heads/master
Date: 2020-03-10T16:51:13+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.robotframework/commit/f61bcc7bfb32dc15796101a269c687f405d203d2

Fixed package install error with Python 3.6 without locale.

See https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272

Files changed:
A news/642.bugfix
M setup.py

b'diff --git a/news/642.bugfix b/news/642.bugfix\nnew file mode 100644\nindex 0000000..0473e7d\n--- /dev/null\n+++ b/news/642.bugfix\n@@ -0,0 +1,3 @@\n+Fixed package install error with Python 3.6 without locale.\n+See `coredev issue 642 <https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272>`_.\n+[maurits]\ndiff --git a/setup.py b/setup.py\nindex dcdbb3d..503bf06 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -14,15 +14,29 @@ def indent(line):\n     return \'   \' + line\n \n \n+def read(filename):\n+    with open(filename) as myfile:\n+        try:\n+            return myfile.read()\n+        except UnicodeDecodeError:\n+            # Happens on one Jenkins node on Python 3.6,\n+            # so maybe it happens for users too.\n+            pass\n+    # Opening and reading as text failed, so retry opening as bytes.\n+    with open(filename, "rb") as myfile:\n+        contents = myfile.read()\n+        return contents.decode("utf-8")\n+\n+\n long_description = (\n-    open(\'README.rst\').read() +\n+    read(\'README.rst\') +\n     \'\\n\' +\n     \'Contributors\\n\'\n     \'============\\n\' +\n     \'\\n\' +\n-    open(\'CONTRIBUTORS.rst\').read() +\n+    read(\'CONTRIBUTORS.rst\') +\n     \'\\n\' +\n-    open(\'CHANGES.rst\').read()\n+    read(\'CHANGES.rst\')\n )\n \n \n'

Repository: plone.app.robotframework


Branch: refs/heads/master
Date: 2020-03-10T18:15:16+01:00
Author: Maurits van Rees (mauritsvanrees) <m.van.rees@zestsoftware.nl>
Commit: https://github.com/plone/plone.app.robotframework/commit/fb810e8198372d9c27d471550e200af09f22e43a

Merge pull request #119 from plone/maurits/jenkins-node-4-py36

Fixed package install error with Python 3.6 without locale.

Files changed:
A news/642.bugfix
M setup.py

b'diff --git a/news/642.bugfix b/news/642.bugfix\nnew file mode 100644\nindex 0000000..0473e7d\n--- /dev/null\n+++ b/news/642.bugfix\n@@ -0,0 +1,3 @@\n+Fixed package install error with Python 3.6 without locale.\n+See `coredev issue 642 <https://github.com/plone/buildout.coredev/issues/642#issuecomment-597008272>`_.\n+[maurits]\ndiff --git a/setup.py b/setup.py\nindex dcdbb3d..503bf06 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -14,15 +14,29 @@ def indent(line):\n     return \'   \' + line\n \n \n+def read(filename):\n+    with open(filename) as myfile:\n+        try:\n+            return myfile.read()\n+        except UnicodeDecodeError:\n+            # Happens on one Jenkins node on Python 3.6,\n+            # so maybe it happens for users too.\n+            pass\n+    # Opening and reading as text failed, so retry opening as bytes.\n+    with open(filename, "rb") as myfile:\n+        contents = myfile.read()\n+        return contents.decode("utf-8")\n+\n+\n long_description = (\n-    open(\'README.rst\').read() +\n+    read(\'README.rst\') +\n     \'\\n\' +\n     \'Contributors\\n\'\n     \'============\\n\' +\n     \'\\n\' +\n-    open(\'CONTRIBUTORS.rst\').read() +\n+    read(\'CONTRIBUTORS.rst\') +\n     \'\\n\' +\n-    open(\'CHANGES.rst\').read()\n+    read(\'CHANGES.rst\')\n )\n \n \n'

